//
// Created by morro on 10/1/2026.
//

#ifndef C_PROJECT_01_UNIT_CONVERTER_FUNCTIONS_H
#define C_PROJECT_01_UNIT_CONVERTER_FUNCTIONS_H

void lengthMenu(void);



#endif //C_PROJECT_01_UNIT_CONVERTER_FUNCTIONS_H
